# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="fifimod"
version="${file.jarVersion}"
displayName="Fifi Mod"
credits="Members of FIF INC."
authors="Benjamin Zvolenszki, Peter Kiss"
description='''
Of course I do not have time to write this
'''
[[dependencies.fifimod]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fifimod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
